export const homeobjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTExtDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transations with zero fees",
  desciption:
    "Get acces to our exlusive app that allows you to send unlimted transactions without getting charged any fees.",
  buttonLablel: "Get started",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeobjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTExtDesc: false,
  topLine: "Unlimited Access",
  headline: "Login to your account at any time",
  desciption:
    "we have you covered no matter where you are located.All you need is an internet connection and a pohne or computer",
  buttonLablel: "Learn More",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "car",
  dark: false,
  primary: false,
  darkText: true,
};
export const homeobjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTExtDesc: false,
  topLine: "Join our Team",
  headline: "Creating an account is extremrly easy",
  desciption:
    "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you're ready to go.",
  buttonLablel: "Start Now",
  imgStart: true,
  img: require("../../images/svg-4.svg").default,
  alt: "car",
  dark: false,
  primary: false,
  darkText: true,
};
